"use client";

import { useState, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { generateCoverPageMarkdown } from "@/lib/generateDocument";
import { getDocumentTitle } from "@/lib/documentTypes";
import { getTemplate } from "@/lib/api";

interface DocumentPreviewProps {
  docType: string | null;
  fields: Record<string, string>;
}

export default function DocumentPreview({ docType, fields }: DocumentPreviewProps) {
  const [templateContent, setTemplateContent] = useState<string>("");
  const [loadingTemplate, setLoadingTemplate] = useState(false);

  useEffect(() => {
    if (!docType) {
      setTemplateContent("");
      return;
    }
    setLoadingTemplate(true);
    getTemplate(docType)
      .then(setTemplateContent)
      .catch(() => setTemplateContent(""))
      .finally(() => setLoadingTemplate(false));
  }, [docType]);

  if (!docType) {
    return (
      <div className="flex items-center justify-center h-full min-h-[300px] text-sm" style={{ color: "#888888" }}>
        <div className="text-center">
          <p className="text-lg font-medium" style={{ color: "#032147" }}>
            Document Preview
          </p>
          <p className="mt-2">
            Your document will appear here as you chat with the AI assistant.
          </p>
        </div>
      </div>
    );
  }

  const coverPage = generateCoverPageMarkdown(docType, fields);
  const fullDocument = templateContent
    ? coverPage + "\n\n---\n\n## Standard Terms\n\n" + templateContent
    : coverPage;

  return (
    <div>
      <div className="mb-4 pb-2 border-b border-zinc-200">
        <p className="text-xs font-medium uppercase tracking-wide" style={{ color: "#209dd7" }}>
          {getDocumentTitle(docType)}
        </p>
      </div>
      <div className="prose prose-sm prose-zinc max-w-none">
        {loadingTemplate ? (
          <p className="text-zinc-400">Loading document template...</p>
        ) : (
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{fullDocument}</ReactMarkdown>
        )}
      </div>
      <div
        className="mt-6 pt-4 border-t border-zinc-200 text-xs"
        style={{ color: "#888888" }}
      >
        <strong>Disclaimer:</strong> This document is a draft generated by
        Prelegal and is subject to legal review. It should not be considered
        legal advice. Please consult a qualified attorney before executing any
        legal agreement.
      </div>
    </div>
  );
}
