import { getDocumentTitle, getFieldLabel } from "./documentTypes";
import {
  type NdaFormData,
  defaultFormData,
  generateCoverPage,
  generateStandardTerms,
} from "./generateNda";

/**
 * Generate a cover page / key terms markdown preview for any document type.
 * For mutual_nda, delegates to the existing NDA generator for pixel-identical output.
 * For all other types, builds a generic cover page from the fields dict.
 */
export function generateCoverPageMarkdown(
  docType: string,
  fields: Record<string, string>
): string {
  if (docType === "mutual_nda") {
    return generateNdaCoverPage(fields);
  }
  return generateGenericCoverPage(docType, fields);
}

/**
 * Generate full document markdown (cover page + standard terms for NDA, cover page only for others).
 */
export function generateFullDocumentMarkdown(
  docType: string,
  fields: Record<string, string>
): string {
  if (docType === "mutual_nda") {
    const formData = mapFieldsToNdaFormData(fields);
    return generateCoverPage(formData) + "\n" + generateStandardTerms() + "\n";
  }
  return generateGenericCoverPage(docType, fields);
}

function mapFieldsToNdaFormData(fields: Record<string, string>): NdaFormData {
  return {
    ...defaultFormData,
    ...Object.fromEntries(
      Object.entries(fields).filter(
        ([key]) => key in defaultFormData
      )
    ),
  } as NdaFormData;
}

function generateNdaCoverPage(fields: Record<string, string>): string {
  const formData = mapFieldsToNdaFormData(fields);
  return generateCoverPage(formData) + "\n" + generateStandardTerms() + "\n";
}

function generateGenericCoverPage(
  docType: string,
  fields: Record<string, string>
): string {
  const title = getDocumentTitle(docType);
  const lines: string[] = [`# ${title}`, "", "## Cover Page / Key Terms", ""];

  // Separate party/signer fields from document terms
  const partyFields: [string, string][] = [];
  const termFields: [string, string][] = [];

  for (const [key, value] of Object.entries(fields)) {
    if (!value || !value.trim()) continue;
    if (
      key.toLowerCase().includes("name") &&
      !key.toLowerCase().includes("company")
    ) {
      partyFields.push([key, value]);
    } else {
      termFields.push([key, value]);
    }
  }

  // Render term fields
  if (termFields.length > 0) {
    for (const [key, value] of termFields) {
      lines.push(`**${getFieldLabel(key)}**: ${value}`, "");
    }
  } else {
    lines.push("*No terms specified yet.*", "");
  }

  // Render signature section if we have party info
  if (partyFields.length > 0) {
    lines.push("---", "", "### Signatures", "");
    for (const [key, value] of partyFields) {
      lines.push(`**${getFieldLabel(key)}**: ${value}`, "");
    }
  }

  lines.push(
    "---",
    "",
    `*Generated by Prelegal. This is a draft document subject to legal review.*`
  );

  return lines.join("\n");
}
